# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, builds an image, performs a container image
# scan with Anchore's Syft tool, and uploads the results to the GitHub Dependency
# submission API.
  

name: Syft SBOM Scan 
 
on: 
  push:
    branches: [ "develop" ]

jobs:
  sbom-scan:
    permissions:
      contents: write
    runs-on: on push
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: SPDX Scan
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          artifact-name: spdx.json
          # Add any additional SPDX scan options if available

      - name: CycloneDX Scan
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          artifact-name: cdx.json
          # Add any additional CycloneDX scan options if available
