name: Test Scan 
 
on: 
  push:
    branches: [ "develop" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          # Add commands to install dependencies here
      - name: Build project
        run: |
          # Add commands to build the project here
      - name: SPDX Scan
        id: spdx_scan
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          artifact-name: spdx.json
          # Add any additional SPDX scan options if available
      - name: CycloneDX Scan
        id: cyclonedx_scan
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          artifact-name: cdx.json
          # Add any additional CycloneDX scan options if available

  results:
    name: Results
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload SPDX JSON
        uses: actions/upload-artifact@v2
        with:
          name: spdx-results
          path: spdx.json
      - name: Upload CycloneDX JSON
        uses: actions/upload-artifact@v2
        with:
          name: cyclonedx-results
          path: cdx.json
